name: SkirtsUtil
main: me.curlpipesh.util.Util
version: 0.2.0
description: skirts' plugin for various utilities like SQLite
authors: [skirts]
website: https://curlpipesh.me/
depend: []
loadbefore: [Essentials]

permissions:
  skirts.util.debug:
    description: Allow usage of the debug command
    default: op
